/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/

//Creates an array and fills it with objects that contain quotes and various properties.

var quotes = [
  {
  quote: 'I have bought this wonderful machine- a computer. Now I am rather an authority on gods, so I identified the machine- it seems to me to be an Old Testament god with a lot of rules and no mercy.',
  source: 'Joseph Campbell',
  citation: 'The Power of Myth',
  year: 1988,
  tag: 'computers'
  },
  {
  quote: 'Never underestimate the bandwidth of a station wagon full of tapes hurtling down the highway.',
  source: 'Andrew S. Tanenbaum',
  citation: 'Computer Networks 3rd Ed.',
  year: 1996,
  tag: 'computers'
  },
  {
  quote: "I don't even know how to use a parking meter, let alone a phone box.",
  source: 'Diana, Princess of Wales',
  citation: 'The Times',
  year: 1994,
  tag: "humor"
  },
  {
  quote: 'Life’s barely long enough to get good at one thing. So be careful what you get good at.',
  source: 'Rust Cohle',
  citation: 'True Detective',
  tag: "ability"
  },
  {
  quote: 'There is nothing so ridiculous but some philosopher has said it.',
  source: 'Cicero',
  tag: "philosophy"
  },
  {
  quote: 'Life is like riding a bicycle. To keep your balance you must keep moving.',
  source: 'Albert Einstein',
  year: 1930,
  tag: "advice"
}
]

// Logs the elements of the quotes array into the console for debugging.

console.log(quotes);

/* Creates a function that generates a random number between 0 and the index of the last element of the quotes array.
   Then returns the contents of the array at the index generated by the RNG. */

var getRandomQuote = function (){
  var ranNum = Math.floor(Math.random()*quotes.length);
  return quotes[ranNum];
}
// Logs the randomly selected quote to the console for debugging.
console.log(getRandomQuote());

/* Creates a function that writes the various properties of the object selected by the 'getRandomQuote' function
   to the inner HTML of the DIV element with the 'quote-box' id. The function first checks whether the citation and year
   properties are present within the object before writing these properties. */ 

var printQuote = function(){
  nextQuote = getRandomQuote();
  var quoteString = '';
  quoteString += '<p class="quote">' + nextQuote.quote + '</p>';
  quoteString += '<p class="source">' + nextQuote.source;
  if ('citation' in nextQuote){
    quoteString += '<span class="citation">' + nextQuote.citation + '</span>';
  }
  if ('year' in nextQuote){
    quoteString += '<span class="year">' + nextQuote.year + '</span>';
  }
  quoteString += '</p>';
  document.getElementById("quote-box").innerHTML = quoteString;
}



/***
  When the "Show another quote" button is clicked, the event listener 
  below will be triggered, and it will call, or "invoke", the `printQuote` 
  function. So do not make any changes to the line of code below this 
  comment.
***/

document.getElementById('loadQuote').addEventListener("click", printQuote, false);


// Remember to delete the comments that came with this file, and replace them with your own code comments.